version: '3.8'

services:
  app:
    build: .
    #command: sh -c "sleep 5 && alembic upgrade head"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: de_challenge
    volumes:
    - ./data:/var/lib/postgresql/data\
    #- ./psql/pg-init-scripts:/docker-entrypoint-initdb.d  
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always