"""Added update column trips table

Revision ID: 2e0908a0cfa4
Revises: f28a1f4c179d
Create Date: 2022-08-28 21:34:03.440312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e0908a0cfa4'
down_revision = 'f28a1f4c179d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('upload_datetime', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'upload_datetime')
    # ### end Alembic commands ###
