"""Added trips table

Revision ID: 57241af5e257
Revises: 
Create Date: 2022-08-28 20:16:14.268280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57241af5e257'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('origin_coord', sa.String(), nullable=True),
    sa.Column('destination_coord', sa.String(), nullable=True),
    sa.Column('datetime', sa.String(), nullable=True),
    sa.Column('datasource', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
