"""Added test table

Revision ID: e3a380640ac5
Revises: 
Create Date: 2022-08-27 23:56:06.492849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a380640ac5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_test_id_usuario'), 'test', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_id_usuario'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
