"""Added address columns trips table

Revision ID: f28a1f4c179d
Revises: 57241af5e257
Create Date: 2022-08-28 20:34:38.006418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28a1f4c179d'
down_revision = '57241af5e257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('origin_address', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('destination_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'destination_address')
    op.drop_column('trips', 'origin_address')
    # ### end Alembic commands ###
